### ISSUE TITLE
Does not account for different resolution settings

### ISSUE THREAD

**Issue by hw2007** [lihaoyun6/Logoer#1]
I have my resolution set to "more space" which is causing the logo to appear in the wrong spot. Is it possible to add an option to account for differing resolutions?

I have a MacBook Pro 14" (with notch) running macOS Sonoma 14.5.

Edit: I think the logo may also be very slightly too big on the higher resolution

<img width="703" alt="image" src="https://github.com/user-attachments/assets/40d1f455-f7d7-44f3-be66-eae1f251e955">

**Comment by lihaoyun6** [comment]
<img width="550" alt="image" src="https://github.com/user-attachments/assets/590180cc-1fec-4c6f-b74e-3880b75f9611">

This issue has been fixed in v0.1.2
Logoer can now get the menu bar height of each monitor and place the logo in the correct position
