### ISSUE TITLE
15.0 beta3 emoji图标无法覆盖原苹果图标

### ISSUE THREAD

**Issue by ichinhuang** [lihaoyun6/Logoer#10]
![截屏2024-07-24 15 08 34](https://github.com/user-attachments/assets/ddf9334b-afaa-478c-bc3f-31a90435233c)

**Comment by kunyan** [comment]
macOS 14.5也无法覆盖原图标

**Comment by lihaoyun6** [comment]
因为Logoer只是"覆盖", 没有办法隐藏原本的默认图标. 所以如果你选择的Emoji本身就盖不住的话, 确实会漏出来.  
在下个版本(v0.1.8)中将会加入一个"随机选取"按钮, 会从我测试过的一堆保证可以覆盖住logo的emoji中随机选取并设定

**Comment by lihaoyun6** [comment]
<img width="620" alt="image" src="https://github.com/user-attachments/assets/9c16e54b-d80a-408d-a1b8-ba98d5095e95">

更新v0.2.0并在设置中启用"自动遮蔽", 然后授予Logoer截屏权限, 即可自动遮盖系统默认logo, 让美化效果更进一步!!!
