### ISSUE TITLE
建议：要是能读取前台应用的图标就好了

### ISSUE THREAD

**Issue by zhheo** [lihaoyun6/Logoer#11]
这样菜单显示什么应用，图标就显示什么应用

**Comment by lihaoyun6** [comment]
<img width="261" alt="image" src="https://github.com/user-attachments/assets/5ed3c540-c72f-460e-96e1-0219ec592e45">

可以做到, 这个新功能将在v0.1.8版本中实装

**Comment by lihaoyun6** [comment]
此功能已在v0.1.8版本中实装, 请更新

**Comment by zhheo** [comment]
太强辣！已更新。他在绝大多数应用下都可以正常工作，但是在edge中无法正常显示。
<img width="416" alt="image" src="https://github.com/user-attachments/assets/446db2ca-ebb8-413a-9b5b-0c6d466caf9a">
