### ISSUE TITLE
手动导入的图片只能覆盖apple logo不能替换

### ISSUE THREAD

**Issue by Richert-mark** [lihaoyun6/Logoer#13]
您好，

<img width="396" alt="image" src="https://github.com/user-attachments/assets/243e6383-f434-4dcc-a288-25c0311e8e3b">

我想使用自己的图片进行替换，但是发现一个问题，就是自己导入的图片不能是透明的png，这样会和apple logo重叠，自己只能导入白色背景的jpeg。

目标是使用透明背景的png替换apple logo，这个可以实现么，比如华为logo[手动狗头]

感谢

**Comment by livcm** [comment]
理论上应该不可以，这个软件只是贴了一层图在原图标上

**Comment by Richert-mark** [comment]
发现了，所以拿了一个更大的微软logo把苹果图标盖住了。只是华为菊花标不规则放上去留白不好看，没法ntr

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Qihuan Jun ***@***.***>
发送时间: Thursday, August 1, 2024 11:09:21 PM
收件人: lihaoyun6/Logoer ***@***.***>
抄送: ***@***.*** ***@***.***>; Author ***@***.***>
主题: Re: [lihaoyun6/Logoer] 手动导入的图片只能覆盖apple logo不能替换 (Issue #13)


This is an external email.

理论上应该不可以，这个软件只是贴了一层图在原图标上

―

**Comment by lihaoyun6** [comment]
<img width="620" alt="image" src="https://github.com/user-attachments/assets/9c16e54b-d80a-408d-a1b8-ba98d5095e95">

更新v0.2.0并在设置中启用"自动遮蔽", 然后授予Logoer截屏权限, 即可自动遮盖系统默认logo, 让美化效果更进一步
