### ISSUE TITLE
全屏模式不适配深色背景

### ISSUE THREAD

**Issue by MDX-Tom** [lihaoyun6/Logoer#15]
<img width="136" alt="截屏2024-07-26 11 47 00" src="https://github.com/user-attachments/assets/a3e82747-ed86-4d39-9006-9ca71c6d6b43">
如题，全屏模式下状态栏背景是黑色的，电量指示器的背景是透明的所以其实是个黑色图标

**Comment by lihaoyun6** [comment]
此问题已在 v0.2.1 版本中得到修复, 请更新并检查问题是否得到解决
在 0.2.1 版本中你可以自定义电量指示器模式的背景颜色
