### ISSUE TITLE
应用全屏模式时 logoer 显示应用图标异常

### ISSUE THREAD

**Issue by kelein** [lihaoyun6/Logoer#17]
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/4d50f50f-8554-4849-8585-7a070aa112bb">

<img width="468" alt="image" src="https://github.com/user-attachments/assets/2eb4b40e-2872-471f-b59e-3d1287dbaaae">

如图所示，在应用全屏显示状态下，它的图标没有随状态栏隐藏进去。

**Comment by lihaoyun6** [comment]
此问题已在v0.2.0版本中得到修复, 请更新并检查问题是否得到解决

**Comment by pg-twooo** [comment]
![image](https://github.com/user-attachments/assets/00660ca4-22b8-4f00-97b9-724951340180)
外接屏幕的时候全屏还是有这个问题
![image](https://github.com/user-attachments/assets/e723cb91-59c6-461a-80e8-2480eecbe212)

**Comment by pg-twooo** [comment]
@lihaoyun6

**Comment by lihaoyun6** [comment]
> @lihaoyun6

请提供更多信息, 比如显示器分辨率, 还有具体是什么App全屏的时候出现的问题

**Comment by pg-twooo** [comment]
> > @lihaoyun6
> 
> 请提供更多信息, 比如显示器分辨率, 还有具体是什么App全屏的时候出现的问题

![image](https://github.com/user-attachments/assets/84bdb830-20db-44fc-a181-7c238b7706c1)
macOS: 14.2
扩展屏幕里的所有app全屏都会这样 Chrome、idea

**Comment by pg-twooo** [comment]
Chrome是这样 
![image](https://github.com/user-attachments/assets/f3ca85bc-d5a3-4406-a068-c3da6922acda)
![image](https://github.com/user-attachments/assets/2da7ca8a-eee0-4e15-8bbc-a1770e5db5e6)


![image](https://github.com/user-attachments/assets/4c89fc46-d448-4fc3-87e4-cdb6b366b2a4)
![image](https://github.com/user-attachments/assets/0d9c1d03-58ee-40be-9b76-e613f68087cc)

这是IDEA

**Comment by pg-twooo** [comment]
关了这个就没问题了 
![image](https://github.com/user-attachments/assets/08e87d24-c796-43da-b12e-1ba1785afc2d)
