### ISSUE TITLE
Logo does not appear on external sidecar display when in fullscreen

### ISSUE THREAD

**Issue by hw2007** [lihaoyun6/Logoer#2]
As described in the title, the custom logo does not appear on my iPad Pro 11" connected via sidecar when an app is in fullscreen on the iPad display. Even if I set the ipad to be the "main" display in system settings, the same thing still happens. I do not know if the issue is specific to sidecar, or just external monitors in general as I do not have another monitor to test with. See images below.

MacBook display
<img width="1800" alt="Main" src="https://github.com/user-attachments/assets/51787c6d-12cf-4cf3-8000-c3ad67e14979">

iPad display
<img width="1194" alt="Secondary" src="https://github.com/user-attachments/assets/f758155b-0d74-4a8e-8409-27d2914c32c0">

**Comment by lihaoyun6** [comment]
<img width="400" alt="image" src="https://github.com/user-attachments/assets/988df5c8-b0e2-4af4-af46-eb5d2a1f934d">

In the new version, there will be a new option called "Visible in Full Screen Mode" (off by default).
Enabling it will make the custom logo keep visible when any monitor enters full screen mode.

It will be added to v0.1.4 which will be released later today😁

**Comment by lihaoyun6** [comment]
v0.1.4 has been released!
