### ISSUE TITLE
刷新mask间隔改为0s后卡死

### ISSUE THREAD

**Issue by char1eslu** [lihaoyun6/Logoer#20]
如题，卸载重装没有重置设置。。。

**Comment by char1eslu** [comment]
用app cleaner卸载，清除残留后可以恢复，brew uninstall不行

**Comment by lihaoyun6** [comment]
此问题已经在v0.2.2版本中得到修复. 新版本中将禁止用户把刷新间隔设置为小于1的值.  
并且我也更新了brew源数据, 包含了配置文件的清理项目. 使用brew uninstall卸载的时候会自动清理残留的设置项
