### ISSUE TITLE
Logoer >=0.1.3 not starting on macos 14.5

### ISSUE THREAD

**Issue by wfsg00098** [lihaoyun6/Logoer#3]
Logoer >=0.1.3 not starting on macos 14.5 m2 pro
LogoerHelper will infinity restart when it is killed.

upgraded from logoer=0.1.1, and it works when revert back to 0.1.1

**Comment by wfsg00098** [comment]
[Logoer-2024-07-21-191756.txt](https://github.com/user-attachments/files/16324011/Logoer-2024-07-21-191756.txt)
Crash log is here
replace .txt to .ips to open in macos debug console

**Comment by lihaoyun6** [comment]
Logoer v0.1.5 has been released. Now it can work properly on Macs without built-in battery.
Please update and try it out😁

**Comment by wfsg00098** [comment]
Good. But another problem occurs.
On macos 15, the icon will shift upward as the image shows
![Uploading QQ_1721577167809.png…]()

**Comment by lihaoyun6** [comment]
> Good. But another problem occurs.
> On macos 15, the icon will shift upward as the image shows

This has been fixed in v0.1.6

**Comment by wfsg00098** [comment]
Solved
