### ISSUE TITLE
多桌面修改不成功

### ISSUE THREAD

**Issue by char1eslu** [lihaoyun6/Logoer#5]
开了 Visible in Full Screen Mode 这个后才能所有桌面更改成功，但是又有点奇怪，左上角有个标；不开的话，只能在软件操作当前桌面修改成功，其他桌面还是原样

**Comment by lihaoyun6** [comment]
由于macOS窗口管理机制限制，暂时确实只能做到这种程度了，抱歉

**Comment by miloweimo** [comment]
确实 我也发现了

**Comment by char1eslu** [comment]
> 由于macOS窗口管理机制限制，暂时确实只能做到这种程度了，抱歉

好吧，谢谢
