### ISSUE TITLE
Mac mini 15.0 Beta (24A5289h)上图标有点向上偏移

### ISSUE THREAD

**Issue by skyrocketingHong** [lihaoyun6/Logoer#6]
![c1922b30c0b5d954b3df7d22f3e76e28](https://github.com/user-attachments/assets/6233ce01-15e9-4eed-83c1-0bd9f9f898db)

**Comment by lihaoyun6** [comment]
好的，我会检查一下

**Comment by lihaoyun6** [comment]
此问题已修复
